# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1438007214);
user_pref("app.update.lastUpdateTime.background-update-timer", 1438006966);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1438007336);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1438010315);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1438007093);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1438006836);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "CA");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150630154324");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1438109867");
user_pref("browser.slowStartup.averageTime", 1021);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150630154324");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"toggle-button--cenorouterequalitie-ceno-toggle\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"toggle-button--cenorouterequalitie-ceno-toggle\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1438109929028");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1438109929642");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1438196329642");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1438109877601");
user_pref("datareporting.policy.firstRunTime", "1438006587233");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 755);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 947);
user_pref("datareporting.sessions.current.startTime", "1438109866642");
user_pref("datareporting.sessions.current.totalTime", 103);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"cenorouter@equalit.ie\":{\"version\":\"1.0.0\",\"type\":\"extension\",\"descriptor\":\"/Users/redwire/Developer/Sources/Projects/ceno/browser-profiles/firefox/extensions/cenorouter@equalit.ie.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.cenorouter@equalit.ie.sdk.baseURI", "resource://cenorouter-at-equalit-dot-ie/");
user_pref("extensions.cenorouter@equalit.ie.sdk.domain", "cenorouter-at-equalit-dot-ie");
user_pref("extensions.cenorouter@equalit.ie.sdk.load.reason", "downgrade");
user_pref("extensions.cenorouter@equalit.ie.sdk.rootURI", "jar:file:///Users/redwire/Developer/Sources/Projects/ceno/browser-profiles/firefox/extensions/cenorouter@equalit.ie.xpi!/");
user_pref("extensions.cenorouter@equalit.ie.sdk.version", "1.0.0");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1438007224);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"cenorouter@equalit.ie\":{\"d\":\"/Users/redwire/Developer/Sources/Projects/ceno/browser-profiles/firefox/extensions/cenorouter@equalit.ie.xpi\",\"e\":true,\"v\":\"1.0.0\",\"st\":1438109963000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1436112904000,\"mt\":1436112903000}}}");
user_pref("gecko.buildID", "20150630154324");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1438008523);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1438007225);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150630154324");
user_pref("media.gmp-manager.lastCheck", 1438109928);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1438008523);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1438008523);
user_pref("toolkit.startup.last_success", 1438109866);
user_pref("toolkit.telemetry.previousBuildID", "20150630154324");
